---
driver:
  name: ec2
  require_chef_omnibus: 12.17.44
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.2xlarge
  interface: public
  iam_profile_name: test-ebs-attachment
  tags:
    Type: test
    Env: public

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environments: dev

platforms:
  - name: ubuntu-14.04

suites:
  - name: server
    tags:
      Name: et-elk-ubuntu-1404
    run_list:
      - recipe[et_elk_preop]
      - recipe[et_elk::server]
      - role[es_master]
      - recipe[et_elk_postop]
    attributes:
      storage:
        ebs_volumes:
          vol1:
            device: /dev/xvde
            size: 2
            delete_on_termination: true
