---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  config_rb:
    environments: dev

platforms:
  - name: ubuntu-14.04
    attributes:
      elk_forwarder:
        mocking: true
      elk_logstash:
        server:
          elasticsearch:
            host: 127.0.0.1

suites:
  - name: client
    run_list:
      - recipe[apt]
      - recipe[et_elk::client]
  - name: server
    run_list:
      - recipe[apt]
      - recipe[et_elk::server]
      - role[es_master]
