---
driver:
  name: ec2
  require_chef_omnibus: true
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  username: ubuntu
  flavor_id: c3.2xlarge
  interface: public
  tags:
    Name: elk-ubuntu-1404

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_id: ami-92f569fa
      tags:
        Env: public

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[elk::default]
    attributes:
      apt:
        compile_time_update: true
